### ISSUE TITLE
Release 2.0 Main Tracking issue

### ISSUE THREAD

**Issue by josalhor** [josalhor/WebProjectOne#15]
- [x]  Fix previous issues
    - [x] Improve docker compose (name, restart, environment variables, etc)
    - [x] Improve directory structure 
    - [x] Maybe document Travis -> Docker deployment?
    - [x] Change the structure to dev branch
    - [x] Docker Run User
    - [x] Define commit name strategies
    - [x] Add str to models
- [x] API
    - [x] Check and research current code
    - [x] Find long term fix for ENV
    - [x] Integrate API calls in lazy mode
    - [x] Integrate API into search if possible
- [x] User Interaction
    - [x] Define User-Comment-Book relationship (multiple comments per book?)
    - [x] Research AJAX and JQUERY integration
    - [x] Book comment interaction
        - [x] Integrate box to add comments
        - [x] Integrate box to remove comments
        - [x] Integrate box to edit comments
    - [x] Account interaction
        - [x] Integrate way to modify account
            - [x] Modify username/email
            - [x] Modify password
        - [x] Integrate way to delete account
    - [x] Book interaction
        - [x] Wish item
        - [x] Unwish item
- [x] Integration tests 
    - [x] Research Behave
    - [x] Research Splinter
    - [x] Demo Behave and Splinter usage
    - [x] Testing
        - [x] Basic navigation
            - [x] Main page
            - [x] Book
            - [x] Category
            - [x] User
            - [x] Search
        - [x] Testing User
            - [x] User creation
            - [x] User editing
            - [x] User deletion
        - [x] Book
            - [x] Comment visualization
            - [x] Comment adding info
            - [x] Comment editing info
            - [x] Comment deleting

**Comment by josalhor** [comment]
Expected plan:
- [ ] Fix previous issues 2020/04/05
- [ ] Basic research and work distribution done 2020/04/07
- [ ] Basic API done 2020/04/08
- [ ] Basic Demo Ajax/Jquery 2020/04/09
- [ ] Account modification done 2020/04/09
- [ ] Demo Behave/Splinter done 2020/04/09
- [ ] Basic integration django tests done 2020/04/10

- [ ] TODO: Define middle of the road plan as we get more info about exams

- [ ] Functionality done expecting validation and testing for 2020/04/23
- [ ] Expect no major changes, Release Candidate for 2020/04/27
- [ ] Branch, final release, present on 2020/05/11

**Comment by josalhor** [comment]
Done
